// <auto-generated />
namespace BlogSyStem.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class updateId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateId));
        
        string IMigrationMetadata.Id
        {
            get { return "202110130442043_updateId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
